- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - run
    - deploy
    - gpt-proxy
    - --image
    - us-central1-docker.pkg.dev/$PROJECT_ID/roboticartifact/gpt-proxy:$COMMIT_SHA
    - --region
    - us-central1
    - --allow-unauthenticated
    - --platform
    - managed
